/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/primitives/Alert.vue')['default']
    AuroraBackground: typeof import('./components/effects/AuroraBackground.vue')['default']
    Avatar: typeof import('./components/primitives/Avatar.vue')['default']
    Badge: typeof import('./components/primitives/Badge.vue')['default']
    BentoGrid: typeof import('./components/effects/BentoGrid.vue')['default']
    BentoItem: typeof import('./components/effects/BentoItem.vue')['default']
    Breadcrumb: typeof import('./components/patterns/Breadcrumb.vue')['default']
    Button: typeof import('./components/primitives/Button.vue')['default']
    Checkbox: typeof import('./components/primitives/Checkbox.vue')['default']
    CommandPalette: typeof import('./components/patterns/CommandPalette.vue')['default']
    DataTable: typeof import('./components/patterns/DataTable.vue')['default']
    DescriptionList: typeof import('./components/patterns/DescriptionList.vue')['default']
    Divider: typeof import('./components/primitives/Divider.vue')['default']
    EmptyState: typeof import('./components/primitives/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./components/patterns/ErrorBoundary.vue')['default']
    FloatingParticles: typeof import('./components/effects/FloatingParticles.vue')['default']
    FormItem: typeof import('./components/patterns/FormItem.vue')['default']
    FormLayout: typeof import('./components/patterns/FormLayout.vue')['default']
    GlassCard: typeof import('./components/effects/GlassCard.vue')['default']
    GradientText: typeof import('./components/effects/GradientText.vue')['default']
    Input: typeof import('./components/primitives/Input.vue')['default']
    InsetGroup: typeof import('./components/patterns/InsetGroup.vue')['default']
    InsetItem: typeof import('./components/patterns/InsetItem.vue')['default']
    ListRow: typeof import('./components/patterns/ListRow.vue')['default']
    MeshGradient: typeof import('./components/effects/MeshGradient.vue')['default']
    Modal: typeof import('./components/primitives/Modal.vue')['default']
    NotificationPanel: typeof import('./components/patterns/NotificationPanel.vue')['default']
    NumberCounter: typeof import('./components/effects/NumberCounter.vue')['default']
    PageHeader: typeof import('./components/patterns/PageHeader.vue')['default']
    PageLayout: typeof import('./components/patterns/PageLayout.vue')['default']
    Pagination: typeof import('./components/patterns/Pagination.vue')['default']
    ParallaxSection: typeof import('./components/effects/ParallaxSection.vue')['default']
    ProgressBar: typeof import('./components/primitives/ProgressBar.vue')['default']
    ProgressRing: typeof import('./components/primitives/ProgressRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollReveal: typeof import('./components/effects/ScrollReveal.vue')['default']
    SearchBar: typeof import('./components/patterns/SearchBar.vue')['default']
    Section: typeof import('./components/patterns/Section.vue')['default']
    Select: typeof import('./components/primitives/Select.vue')['default']
    ShimmerButton: typeof import('./components/effects/ShimmerButton.vue')['default']
    Skeleton: typeof import('./components/primitives/Skeleton.vue')['default']
    StatCard: typeof import('./components/patterns/StatCard.vue')['default']
    Switch: typeof import('./components/primitives/Switch.vue')['default']
    Tag: typeof import('./components/primitives/Tag.vue')['default']
    ThemeSwitcher: typeof import('./components/patterns/ThemeSwitcher.vue')['default']
    Toast: typeof import('./components/primitives/Toast.vue')['default']
    ToastContainer: typeof import('./components/primitives/ToastContainer.vue')['default']
    Tooltip: typeof import('./components/primitives/Tooltip.vue')['default']
    WelcomeWizard: typeof import('./components/patterns/WelcomeWizard.vue')['default']
  }
}
